from pathlib import Path

import pandas as pd
import pytest

from src.optimizer import BulkOptimizer


def _build_synthetic_bulk_file(path: Path) -> None:
    sp_campaigns = pd.DataFrame(
        [
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1001,
                "Ad Group ID": 2001,
                "Keyword ID": 3001,
                "Product Targeting ID": "",
                "Campaign Name": "Camp A",
                "Ad Group Name": "Group A1",
                "Campaign Name (Informational only)": "Camp A",
                "Ad Group Name (Informational only)": "Group A1",
                "Daily Budget": 25.0,
                "Ad Group Default Bid": 0.5,
                "Bid": 0.45,
                "Keyword Text": "daily planner",
                "Match Type": "Broad",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 1200,
                "Clicks": 40,
                "Spend": 30.0,
                "Sales": 120.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1001,
                "Ad Group ID": 2002,
                "Keyword ID": 3002,
                "Product Targeting ID": "",
                "Campaign Name": "Camp A",
                "Ad Group Name": "Group A2",
                "Campaign Name (Informational only)": "Camp A",
                "Ad Group Name (Informational only)": "Group A2",
                "Daily Budget": 25.0,
                "Ad Group Default Bid": 0.5,
                "Bid": 0.35,
                "Keyword Text": "weekly planner",
                "Match Type": "Exact",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 900,
                "Clicks": 28,
                "Spend": 21.0,
                "Sales": 70.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1002,
                "Ad Group ID": 2101,
                "Keyword ID": 3003,
                "Product Targeting ID": "",
                "Campaign Name": "Camp B",
                "Ad Group Name": "Group B1",
                "Campaign Name (Informational only)": "Camp B",
                "Ad Group Name (Informational only)": "Group B1",
                "Daily Budget": 30.0,
                "Ad Group Default Bid": 0.6,
                "Bid": 0.0,
                "Keyword Text": "daily planner",
                "Match Type": "Broad",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 1400,
                "Clicks": 50,
                "Spend": 40.0,
                "Sales": 150.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1002,
                "Ad Group ID": 2102,
                "Keyword ID": 3004,
                "Product Targeting ID": "",
                "Campaign Name": "Camp B",
                "Ad Group Name": "Group B2",
                "Campaign Name (Informational only)": "Camp B",
                "Ad Group Name (Informational only)": "Group B2",
                "Daily Budget": 30.0,
                "Ad Group Default Bid": 0.6,
                "Bid": 0.20,
                "Keyword Text": "agenda notebook",
                "Match Type": "Phrase",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 180,
                "Clicks": 0,
                "Spend": 0.0,
                "Sales": 0.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1003,
                "Ad Group ID": 2201,
                "Keyword ID": 3005,
                "Product Targeting ID": "",
                "Campaign Name": "Camp C",
                "Ad Group Name": "Group C1",
                "Campaign Name (Informational only)": "Camp C",
                "Ad Group Name (Informational only)": "Group C1",
                "Daily Budget": 18.0,
                "Ad Group Default Bid": 0.4,
                "Bid": 0.22,
                "Keyword Text": "work journal",
                "Match Type": "Broad",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 70,
                "Clicks": 0,
                "Spend": 0.0,
                "Sales": 0.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Keyword",
                "Operation": "",
                "Campaign ID": 1003,
                "Ad Group ID": 2202,
                "Keyword ID": 3006,
                "Product Targeting ID": "",
                "Campaign Name": "Camp C",
                "Ad Group Name": "Group C2",
                "Campaign Name (Informational only)": "Camp C",
                "Ad Group Name (Informational only)": "Group C2",
                "Daily Budget": 18.0,
                "Ad Group Default Bid": 0.4,
                "Bid": 0.31,
                "Keyword Text": "planner notebook",
                "Match Type": "Exact",
                "Product Targeting Expression": "",
                "Resolved Product Targeting Expression (Informational only)": "",
                "Impressions": 560,
                "Clicks": 12,
                "Spend": 9.0,
                "Sales": 15.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Product Targeting",
                "Operation": "",
                "Campaign ID": 1004,
                "Ad Group ID": 2301,
                "Keyword ID": "",
                "Product Targeting ID": 9001,
                "Campaign Name": "Camp D",
                "Ad Group Name": "Group D1",
                "Campaign Name (Informational only)": "Camp D",
                "Ad Group Name (Informational only)": "Group D1",
                "Daily Budget": 20.0,
                "Ad Group Default Bid": 0.5,
                "Bid": 0.42,
                "Keyword Text": "",
                "Match Type": "",
                "Product Targeting Expression": 'asin="B0TEST0001"',
                "Resolved Product Targeting Expression (Informational only)": 'asin="B0TEST0001"',
                "Impressions": 820,
                "Clicks": 25,
                "Spend": 18.0,
                "Sales": 0.0,
                "State": "enabled",
            },
            {
                "Product": "Sponsored Products",
                "Entity": "Product Targeting",
                "Operation": "",
                "Campaign ID": 1004,
                "Ad Group ID": 2301,
                "Keyword ID": "",
                "Product Targeting ID": 9002,
                "Campaign Name": "Camp D",
                "Ad Group Name": "Group D1",
                "Campaign Name (Informational only)": "Camp D",
                "Ad Group Name (Informational only)": "Group D1",
                "Daily Budget": 20.0,
                "Ad Group Default Bid": 0.5,
                "Bid": 0.38,
                "Keyword Text": "",
                "Match Type": "",
                "Product Targeting Expression": "close-match",
                "Resolved Product Targeting Expression (Informational only)": "close-match",
                "Impressions": 950,
                "Clicks": 30,
                "Spend": 24.0,
                "Sales": 0.0,
                "State": "enabled",
            },
        ]
    )

    sp_search = pd.DataFrame(
        [
            {
                "Customer Search Term": "daily planner",
                "Campaign ID": 1001,
                "Ad Group ID": 2001,
                "Campaign Name (Informational only)": "Camp A",
                "Ad Group Name (Informational only)": "Group A1",
                "Product Targeting ID": "",
                "Product Targeting Expression": "",
                "Impressions": 5000,
                "Clicks": 120,
                "Spend": 90.0,
                "Sales": 220.0,
                "Click-through Rate": 0.024,
                "Conversion Rate": 0.11,
                "ACOS": 0.41,
                "ROAS": 2.44,
                "CPC": 0.75,
            },
            {
                "Customer Search Term": "weekly planner",
                "Campaign ID": 1001,
                "Ad Group ID": 2002,
                "Campaign Name (Informational only)": "Camp A",
                "Ad Group Name (Informational only)": "Group A2",
                "Product Targeting ID": "",
                "Product Targeting Expression": "",
                "Impressions": 4200,
                "Clicks": 95,
                "Spend": 65.0,
                "Sales": 180.0,
                "Click-through Rate": 0.023,
                "Conversion Rate": 0.13,
                "ACOS": 0.36,
                "ROAS": 2.77,
                "CPC": 0.68,
            },
            {
                "Customer Search Term": "work planner",
                "Campaign ID": 1002,
                "Ad Group ID": 2101,
                "Campaign Name (Informational only)": "Camp B",
                "Ad Group Name (Informational only)": "Group B1",
                "Product Targeting ID": "",
                "Product Targeting Expression": "",
                "Impressions": 3500,
                "Clicks": 70,
                "Spend": 55.0,
                "Sales": 80.0,
                "Click-through Rate": 0.020,
                "Conversion Rate": 0.07,
                "ACOS": 0.69,
                "ROAS": 1.45,
                "CPC": 0.79,
            },
            {
                "Customer Search Term": "agenda notebook",
                "Campaign ID": 1002,
                "Ad Group ID": 2102,
                "Campaign Name (Informational only)": "Camp B",
                "Ad Group Name (Informational only)": "Group B2",
                "Product Targeting ID": "",
                "Product Targeting Expression": "",
                "Impressions": 2800,
                "Clicks": 40,
                "Spend": 40.0,
                "Sales": 25.0,
                "Click-through Rate": 0.014,
                "Conversion Rate": 0.03,
                "ACOS": 1.60,
                "ROAS": 0.62,
                "CPC": 1.00,
            },
            {
                "Customer Search Term": "planner organizer",
                "Campaign ID": 1003,
                "Ad Group ID": 2201,
                "Campaign Name (Informational only)": "Camp C",
                "Ad Group Name (Informational only)": "Group C1",
                "Product Targeting ID": "",
                "Product Targeting Expression": "",
                "Impressions": 1500,
                "Clicks": 20,
                "Spend": 24.0,
                "Sales": 0.0,
                "Click-through Rate": 0.013,
                "Conversion Rate": 0.00,
                "ACOS": 0.0,
                "ROAS": 0.0,
                "CPC": 1.20,
            },
            {
                "Customer Search Term": "product target asin 1",
                "Campaign ID": 1004,
                "Ad Group ID": 2301,
                "Campaign Name (Informational only)": "Camp D",
                "Ad Group Name (Informational only)": "Group D1",
                "Product Targeting ID": 9001,
                "Product Targeting Expression": 'asin="B0TEST0001"',
                "Impressions": 1200,
                "Clicks": 28,
                "Spend": 20.0,
                "Sales": 0.0,
                "Click-through Rate": 0.023,
                "Conversion Rate": 0.00,
                "ACOS": 0.0,
                "ROAS": 0.0,
                "CPC": 0.71,
            },
            {
                "Customer Search Term": "product target auto close",
                "Campaign ID": 1004,
                "Ad Group ID": 2301,
                "Campaign Name (Informational only)": "Camp D",
                "Ad Group Name (Informational only)": "Group D1",
                "Product Targeting ID": 9002,
                "Product Targeting Expression": "close-match",
                "Impressions": 1800,
                "Clicks": 35,
                "Spend": 28.0,
                "Sales": 0.0,
                "Click-through Rate": 0.019,
                "Conversion Rate": 0.00,
                "ACOS": 0.0,
                "ROAS": 0.0,
                "CPC": 0.80,
            },
        ]
    )

    with pd.ExcelWriter(path, engine="xlsxwriter") as writer:
        sp_campaigns.to_excel(writer, sheet_name="Sponsored Products Campaigns", index=False)
        sp_search.to_excel(writer, sheet_name="SP Search Term Report", index=False)


@pytest.fixture(scope="session")
def sample_file_path() -> Path:
    sample_dir = Path(__file__).resolve().parents[1] / "outputs" / ".pytest_samples"
    sample_dir.mkdir(parents=True, exist_ok=True)
    sample_path = sample_dir / "bulk-synthetic-20260101-20260131.xlsx"
    if not sample_path.exists():
        _build_synthetic_bulk_file(sample_path)
    return sample_path


@pytest.fixture
def optimizer(sample_file_path: Path) -> BulkOptimizer:
    opt = BulkOptimizer(str(sample_file_path), enforce_48hr_rule=False, enable_logging=False)
    opt.load_data()
    return opt
