[theme]
base = "dark"
primaryColor = "#0E7490"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E2E8F0"
font = "sans serif"

[server]
maxUploadSize = 400
headless = true
